import { describe, it, expect } from 'vitest';
import { findHardcodedHex } from '../src/lib/guards';
import { clampFraming, generateCss } from '../src/panel/cssGenerator';
import type { PanelState } from '../src/panel/types';

const empty: PanelState = { images: {}, styles: {} };

describe('clampFraming', () => {
  it('keeps in-range values untouched', () => {
    expect(clampFraming(42, 61, 1.12)).toEqual({ x: 42, y: 61, zoom: 1.12 });
  });

  it('never allows zoom below 1, which would expose empty frame', () => {
    expect(clampFraming(50, 50, 0.4).zoom).toBe(1);
  });

  it('caps zoom so a slot cannot be zoomed into mush', () => {
    expect(clampFraming(50, 50, 99).zoom).toBe(4);
  });

  it('clamps pan to the 0-100% range object-fit: cover guarantees is safe', () => {
    expect(clampFraming(-30, 140, 1)).toEqual({ x: 0, y: 100, zoom: 1 });
  });

  it('rounds to two decimals so diffs stay readable', () => {
    expect(clampFraming(42.98765, 61.00001, 1.129999)).toEqual({ x: 42.99, y: 61, zoom: 1.13 });
  });
});

describe('generateCss', () => {
  it('emits only the header when there is nothing to write', () => {
    const css = generateCss(empty);
    expect(css).toContain('GENERATED by the visual editing panel');
    expect(css).not.toContain('object-position');
  });

  it('emits a framing rule keyed on the slot data-label', () => {
    const css = generateCss({
      images: { 'Hero L1 — jungle-far': { x: 42, y: 61, zoom: 1.12 } },
      styles: {},
    });
    expect(css).toContain('.frame[data-label="Hero L1 — jungle-far"] img');
    expect(css).toContain('object-position: 42% 61%;');
    expect(css).toContain('--img-zoom: 1.12;');
  });

  it('omits a zoom declaration when zoom is exactly 1', () => {
    const css = generateCss({ images: { A: { x: 10, y: 20, zoom: 1 } }, styles: {} });
    expect(css).toContain('object-position: 10% 20%;');
    expect(css).not.toContain('--img-zoom');
  });

  it('escapes quotes and backslashes in a slot label', () => {
    const css = generateCss({ images: { 'He said "hi" \\ bye': { x: 0, y: 0, zoom: 1 } }, styles: {} });
    expect(css).toContain('[data-label="He said \\"hi\\" \\\\ bye"]');
  });

  it('emits typography and colour as token references, never literals', () => {
    const css = generateCss({
      images: {},
      styles: { 'hero.intro': { font: 'body', step: 'lede', color: 'fg-dim' } },
    });
    expect(css).toContain('[data-edit="hero.intro"]');
    expect(css).toContain('font-family: var(--font-body);');
    expect(css).toContain('font-size: var(--step-lede);');
    expect(css).toContain('color: var(--fg-dim);');
  });

  it('NEVER emits a colour literal — the guard that keeps the token rule true', () => {
    const css = generateCss({
      images: { A: { x: 1, y: 2, zoom: 1.5 } },
      styles: { b: { font: 'display', step: 'h1', color: 'accent' } },
    });
    expect(findHardcodedHex(css)).toEqual([]);
    expect(css).not.toMatch(/#[0-9a-f]{3,8}\b/i);
    expect(css).not.toMatch(/\brgba?\(/);
  });

  it('sorts keys so two identical states produce byte-identical files', () => {
    const a = generateCss({ images: { b: { x: 1, y: 1, zoom: 1 }, a: { x: 2, y: 2, zoom: 1 } }, styles: {} });
    const b = generateCss({ images: { a: { x: 2, y: 2, zoom: 1 }, b: { x: 1, y: 1, zoom: 1 } }, styles: {} });
    expect(a).toBe(b);
  });

  it('skips colour tokens that are not in the valid set (Finding 1 — runtime validation)', () => {
    // A crafted value attempting to inject CSS should not escape the var() call
    const css = generateCss({
      images: {},
      styles: { test: { color: 'x); } body{background:#000} /*' as any } },
    });
    // The invalid color key should be skipped, so no color declaration at all
    expect(css).not.toContain('color:');
    expect(css).not.toContain('background:');
    expect(findHardcodedHex(css)).toEqual([]);
  });

  it('skips font tokens that are not in the valid set', () => {
    const css = generateCss({
      images: {},
      styles: { test: { font: 'invalid-font' as any } },
    });
    // The invalid font key should be skipped
    expect(css).not.toContain('font-family:');
  });

  it('skips step tokens that are not in the valid set', () => {
    const css = generateCss({
      images: {},
      styles: { test: { step: 'invalid-step' as any } },
    });
    // The invalid step key should be skipped
    expect(css).not.toContain('font-size:');
  });

  it('re-clamps non-finite framing values from storage (Finding 1 — number validation)', () => {
    // Non-finite numbers should be re-clamped to valid range
    const css = generateCss({
      images: { test: { x: NaN, y: Infinity, zoom: -Infinity } },
      styles: {},
    });
    // Should produce a valid rule with clamped values
    expect(css).toContain('object-position:');
    expect(css).not.toContain('NaN');
    expect(css).not.toContain('Infinity');
  });

  it('escapes newlines in slot labels to produce valid CSS (Finding 2)', () => {
    const css = generateCss({
      images: { 'A\nBeef': { x: 0, y: 0, zoom: 1 } },
      styles: {},
    });
    // Newline should be escaped as \a SPACE (with terminating space to stop hex consumption)
    // Without the space, \aBeef would parse as a single 5-hex-digit escape consuming "Beef"
    expect(css).toContain('\\a ');
    expect(css).toContain('[data-label="A\\a Beef"]');
  });

  it('escapes carriage returns in slot labels with proper termination', () => {
    const css = generateCss({
      images: { 'A\r5': { x: 0, y: 0, zoom: 1 } },
      styles: {},
    });
    // Carriage return should be escaped as \d SPACE (with terminating space)
    // Without the space, \d5 would be a 2-hex-digit escape
    expect(css).toContain('\\d ');
    expect(css).toContain('[data-label="A\\d 5"]');
  });

  it('rejects prototype properties as colour tokens (Finding 3)', () => {
    const css = generateCss({
      images: {},
      styles: { test: { color: 'constructor' as any, font: 'toString' as any, step: '__proto__' as any } },
    });
    // Prototype pollution attempt: these should all be rejected
    expect(css).not.toContain('var(--constructor)');
    expect(css).not.toContain('var(--font-toString)');
    expect(css).not.toContain('var(--step-__proto__)');
    // Should emit only the header since all tokens are invalid
    expect(css).toContain('GENERATED by the visual editing panel');
  });
});
