import { describe, it, expect } from 'vitest';
import { findHardcodedHex } from '../src/lib/guards';
import { clampFraming, generateCss, maxPanPercent } from '../src/panel/cssGenerator';
import type { PanelState } from '../src/panel/types';

const empty: PanelState = { images: {}, styles: {}, text: {} };

describe('clampFraming', () => {
  it('keeps in-range values untouched', () => {
    expect(clampFraming(42, 61, 1.12)).toEqual({ x: 42, y: 61, zoom: 1.12 });
  });

  it('never allows zoom below 1, which would expose empty frame', () => {
    expect(clampFraming(50, 50, 0.4).zoom).toBe(1);
  });

  it('caps zoom so a slot cannot be zoomed into mush', () => {
    expect(clampFraming(50, 50, 99).zoom).toBe(4);
  });

  it('clamps pan to the 0-100% range object-fit: cover guarantees is safe', () => {
    expect(clampFraming(-30, 140, 1)).toEqual({ x: 0, y: 100, zoom: 1 });
  });

  it('rounds to two decimals so diffs stay readable', () => {
    expect(clampFraming(42.98765, 61.00001, 1.129999)).toEqual({ x: 42.99, y: 61, zoom: 1.13 });
  });
});

describe('maxPanPercent', () => {
  it('is zero at zoom 1 — pan is impossible when unzoomed', () => {
    expect(maxPanPercent(1)).toBe(0);
  });

  it('grows with zoom, capping at 37.5% at the 4x ceiling', () => {
    expect(maxPanPercent(2)).toBeCloseTo(25, 10);
    expect(maxPanPercent(4)).toBeCloseTo(37.5, 10);
  });
});

describe('clampFraming — pan', () => {
  it('omits pan entirely when it rounds to zero, same as an untouched zoom', () => {
    expect(clampFraming(50, 50, 2, 0, 0)).toEqual({ x: 50, y: 50, zoom: 2 });
  });

  it('forces pan to zero at zoom 1 regardless of what was asked for', () => {
    // A stored pan from a session that later zoomed back out must not linger
    // and silently do nothing useful — it is dropped, not just ignored.
    expect(clampFraming(50, 50, 1, 40, -40)).toEqual({ x: 50, y: 50, zoom: 1 });
  });

  it('clamps pan to the zoom-dependent bound so empty frame can never show', () => {
    // maxPanPercent(2) === 25
    expect(clampFraming(50, 50, 2, 999, -999)).toEqual({ x: 50, y: 50, zoom: 2, panX: 25, panY: -25 });
  });

  it('keeps an in-range pan untouched', () => {
    expect(clampFraming(50, 50, 4, 10, -20)).toEqual({ x: 50, y: 50, zoom: 4, panX: 10, panY: -20 });
  });

  it('sanitizes a non-finite pan to 0 rather than propagating NaN', () => {
    expect(clampFraming(50, 50, 2, NaN, Infinity)).toEqual({ x: 50, y: 50, zoom: 2 });
  });
});

describe('clampFraming — frame trim (height + anchor)', () => {
  it('leaves frameHeight/frameAnchor off entirely when not asked for, byte-identical to before the control existed', () => {
    expect(clampFraming(50, 50, 1)).toEqual({ x: 50, y: 50, zoom: 1 });
  });

  it('omits both fields when height clamps back up to 100 — "no trim" reads as untouched', () => {
    expect(clampFraming(50, 50, 1, 0, 0, 100, 20)).toEqual({ x: 50, y: 50, zoom: 1 });
  });

  it('keeps an in-range height and a non-default anchor', () => {
    expect(clampFraming(50, 50, 1, 0, 0, 40, 20)).toEqual({ x: 50, y: 50, zoom: 1, frameHeight: 40, frameAnchor: 20 });
  });

  it('omits anchor when it is exactly the 50 (centered) default', () => {
    expect(clampFraming(50, 50, 1, 0, 0, 40, 50)).toEqual({ x: 50, y: 50, zoom: 1, frameHeight: 40 });
  });

  it('defaults anchor to centered (omitted) when not supplied at all', () => {
    expect(clampFraming(50, 50, 1, 0, 0, 40)).toEqual({ x: 50, y: 50, zoom: 1, frameHeight: 40 });
  });

  it('floors height at 15 so a band can never shrink to nothing', () => {
    expect(clampFraming(50, 50, 1, 0, 0, 2)).toEqual({ x: 50, y: 50, zoom: 1, frameHeight: 15 });
  });

  it('clamps anchor to 0-100', () => {
    expect(clampFraming(50, 50, 1, 0, 0, 40, -30)).toEqual({ x: 50, y: 50, zoom: 1, frameHeight: 40, frameAnchor: 0 });
    expect(clampFraming(50, 50, 1, 0, 0, 40, 999)).toEqual({ x: 50, y: 50, zoom: 1, frameHeight: 40, frameAnchor: 100 });
  });

  it('sanitizes a non-finite height/anchor rather than propagating NaN', () => {
    expect(clampFraming(50, 50, 1, 0, 0, NaN, Infinity)).toEqual({ x: 50, y: 50, zoom: 1 });
  });
});

describe('generateCss', () => {
  it('emits only the header when there is nothing to write', () => {
    const css = generateCss(empty);
    expect(css).toContain('GENERATED by the visual editing panel');
    expect(css).not.toContain('object-position');
  });

  it('emits a framing rule keyed on the slot data-label', () => {
    const css = generateCss({
      images: { 'Hero L1 — jungle-far': { x: 42, y: 61, zoom: 1.12 } },
      styles: {},
      text: {},
    });
    expect(css).toContain('.frame[data-label="Hero L1 — jungle-far"] img');
    expect(css).toContain('object-position: 42% 61%;');
    expect(css).toContain('--img-zoom: 1.12;');
  });

  it('omits a zoom declaration when zoom is exactly 1', () => {
    const css = generateCss({ images: { A: { x: 10, y: 20, zoom: 1 } }, styles: {}, text: {} });
    expect(css).toContain('object-position: 10% 20%;');
    expect(css).not.toContain('--img-zoom');
  });

  it('emits pan translate declarations when zoom exceeds 1 and pan is nonzero', () => {
    const css = generateCss({
      images: { A: { x: 50, y: 50, zoom: 2, panX: 10, panY: -5 } },
      styles: {},
      text: {},
    });
    expect(css).toContain('--img-zoom: 2;');
    expect(css).toContain('--img-pan-x: 10%;');
    expect(css).toContain('--img-pan-y: -5%;');
  });

  it('omits pan declarations when pan is zero, even at zoom > 1', () => {
    const css = generateCss({ images: { A: { x: 50, y: 50, zoom: 2 } }, styles: {}, text: {} });
    expect(css).not.toContain('--img-pan');
  });

  it('omits pan declarations for an unzoomed frame — identical to before pan existed', () => {
    const css = generateCss({ images: { A: { x: 50, y: 50, zoom: 1, panX: 40, panY: 40 } }, styles: {}, text: {} });
    expect(css).not.toContain('--img-zoom');
    expect(css).not.toContain('--img-pan');
    expect(css).toBe(generateCss({ images: { A: { x: 50, y: 50, zoom: 1 } }, styles: {}, text: {} }));
  });

  it('escapes quotes and backslashes in a slot label', () => {
    const css = generateCss({ images: { 'He said "hi" \\ bye': { x: 0, y: 0, zoom: 1 } }, styles: {}, text: {} });
    expect(css).toContain('[data-label="He said \\"hi\\" \\\\ bye"]');
  });

  it('emits typography and colour as token references, never literals', () => {
    const css = generateCss({
      images: {},
      styles: { 'hero.intro': { font: 'body', step: 'lede', color: 'fg-dim' } },
      text: {},
    });
    expect(css).toContain('[data-edit="hero.intro"]');
    expect(css).toContain('font-family: var(--font-body);');
    expect(css).toContain('font-size: var(--step-lede);');
    expect(css).toContain('color: var(--fg-dim);');
  });

  it('NEVER emits a colour literal — the guard that keeps the token rule true', () => {
    const css = generateCss({
      images: { A: { x: 1, y: 2, zoom: 1.5 } },
      styles: { b: { font: 'display', step: 'h1', color: 'accent' } },
      text: {},
    });
    expect(findHardcodedHex(css)).toEqual([]);
    expect(css).not.toMatch(/#[0-9a-f]{3,8}\b/i);
    expect(css).not.toMatch(/\brgba?\(/);
  });

  it('sorts keys so two identical states produce byte-identical files', () => {
    const a = generateCss({ images: { b: { x: 1, y: 1, zoom: 1 }, a: { x: 2, y: 2, zoom: 1 } }, styles: {}, text: {} });
    const b = generateCss({ images: { a: { x: 2, y: 2, zoom: 1 }, b: { x: 1, y: 1, zoom: 1 } }, styles: {}, text: {} });
    expect(a).toBe(b);
  });

  it('skips colour tokens that are not in the valid set (Finding 1 — runtime validation)', () => {
    // A crafted value attempting to inject CSS should not escape the var() call
    const css = generateCss({
      images: {},
      styles: { test: { color: 'x); } body{background:#000} /*' as any } },
      text: {},
    });
    // The invalid color key should be skipped, so no color declaration at all
    expect(css).not.toContain('color:');
    expect(css).not.toContain('background:');
    expect(findHardcodedHex(css)).toEqual([]);
  });

  it('skips font tokens that are not in the valid set', () => {
    const css = generateCss({
      images: {},
      styles: { test: { font: 'invalid-font' as any } },
      text: {},
    });
    // The invalid font key should be skipped
    expect(css).not.toContain('font-family:');
  });

  it('skips step tokens that are not in the valid set', () => {
    const css = generateCss({
      images: {},
      styles: { test: { step: 'invalid-step' as any } },
      text: {},
    });
    // The invalid step key should be skipped
    expect(css).not.toContain('font-size:');
  });

  it('re-clamps non-finite framing values from storage (Finding 1 — number validation)', () => {
    // Non-finite numbers should be re-clamped to valid range
    const css = generateCss({
      images: { test: { x: NaN, y: Infinity, zoom: -Infinity } },
      styles: {},
      text: {},
    });
    // Should produce a valid rule with clamped values
    expect(css).toContain('object-position:');
    expect(css).not.toContain('NaN');
    expect(css).not.toContain('Infinity');
  });

  it('escapes newlines in slot labels to produce valid CSS (Finding 2)', () => {
    const css = generateCss({
      images: { 'A\nBeef': { x: 0, y: 0, zoom: 1 } },
      styles: {},
      text: {},
    });
    // Newline should be escaped as \a SPACE (with terminating space to stop hex consumption)
    // Without the space, \aBeef would parse as a single 5-hex-digit escape consuming "Beef"
    expect(css).toContain('\\a ');
    expect(css).toContain('[data-label="A\\a Beef"]');
  });

  it('escapes carriage returns in slot labels with proper termination', () => {
    const css = generateCss({
      images: { 'A\r5': { x: 0, y: 0, zoom: 1 } },
      styles: {},
      text: {},
    });
    // Carriage return should be escaped as \d SPACE (with terminating space)
    // Without the space, \d5 would be a 2-hex-digit escape
    expect(css).toContain('\\d ');
    expect(css).toContain('[data-label="A\\d 5"]');
  });

  it('emits a frame-box rule, keyed on the slot label but targeting the frame itself, not its img', () => {
    const css = generateCss({
      images: { 'Hero L5 — jungle-near': { x: 50, y: 50, zoom: 1, frameHeight: 40, frameAnchor: 0 } },
      styles: {},
      text: {},
    });
    expect(css).toContain('.frame[data-label="Hero L5 — jungle-near"] {\n  height: 40%;\n  top: 0%;\n}');
  });

  it('places the anchored band at the bottom when anchor is 100, cropping the top off', () => {
    const css = generateCss({
      images: { A: { x: 50, y: 50, zoom: 1, frameHeight: 40, frameAnchor: 100 } },
      styles: {},
      text: {},
    });
    // 40% tall, pinned to the bottom of the remaining 60% slack.
    expect(css).toContain('height: 40%;\n  top: 60%;');
  });

  it('centers the band (top = half the slack) when anchor is left at 50', () => {
    const css = generateCss({
      images: { A: { x: 50, y: 50, zoom: 1, frameHeight: 40 } },
      styles: {},
      text: {},
    });
    expect(css).toContain('height: 40%;\n  top: 30%;');
  });

  it('emits no frame-box rule at all for an untrimmed slot — untouched renders exactly as before', () => {
    const css = generateCss({ images: { A: { x: 50, y: 50, zoom: 1 } }, styles: {}, text: {} });
    expect(css).not.toContain('height:');
    expect(css).not.toContain('top:');
  });

  it('emits transparent background only when explicitly turned on', () => {
    const on = generateCss({ images: { A: { x: 50, y: 50, zoom: 1, transparentBg: true } }, styles: {}, text: {} });
    expect(on).toContain('.frame[data-label="A"] {\n  background: transparent;\n}');
    const off = generateCss({ images: { A: { x: 50, y: 50, zoom: 1 } }, styles: {}, text: {} });
    expect(off).not.toContain('background:');
  });

  it('combines the trim and background declarations into one frame-box rule', () => {
    const css = generateCss({
      images: { A: { x: 50, y: 50, zoom: 1, frameHeight: 40, frameAnchor: 0, transparentBg: true } },
      styles: {},
      text: {},
    });
    expect(css).toContain('.frame[data-label="A"] {\n  height: 40%;\n  top: 0%;\n  background: transparent;\n}');
    // Exactly one frame-box rule for A, not two.
    expect(css.match(/\.frame\[data-label="A"\] \{/g)).toHaveLength(1);
  });

  it('never emits a colour literal even with trim and background set (guard still holds)', () => {
    const css = generateCss({
      images: { A: { x: 1, y: 2, zoom: 1.5, frameHeight: 33, frameAnchor: 10, transparentBg: true } },
      styles: {},
      text: {},
    });
    expect(findHardcodedHex(css)).toEqual([]);
    expect(css).not.toMatch(/#[0-9a-f]{3,8}\b/i);
    expect(css).not.toMatch(/\brgba?\(/);
  });

  it('re-clamps a corrupted frameHeight/frameAnchor from storage rather than propagating garbage', () => {
    const css = generateCss({
      images: { A: { x: 50, y: 50, zoom: 1, frameHeight: NaN, frameAnchor: Infinity } as any },
      styles: {},
      text: {},
    });
    expect(css).not.toContain('height:');
    expect(css).not.toContain('NaN');
    expect(css).not.toContain('Infinity');
  });

  it('rejects prototype properties as colour tokens (Finding 3)', () => {
    const css = generateCss({
      images: {},
      styles: { test: { color: 'constructor' as any, font: 'toString' as any, step: '__proto__' as any } },
      text: {},
    });
    // Prototype pollution attempt: these should all be rejected
    expect(css).not.toContain('var(--constructor)');
    expect(css).not.toContain('var(--font-toString)');
    expect(css).not.toContain('var(--step-__proto__)');
    // Should emit only the header since all tokens are invalid
    expect(css).toContain('GENERATED by the visual editing panel');
  });
});
