import type { FontKey, StepKey, ColorKey, PanelState, ImageEdit } from './types';

const HEADER = `/* GENERATED by the visual editing panel (src/panel/). Safe to delete or to
   git-checkout wholesale: every rule here is a framing or token choice, never
   structure. Hand edits survive until the next Save, which rewrites the file
   from the panel's state. */
`;

const MIN_ZOOM = 1;
const MAX_ZOOM = 4;

// Runtime allowlists of valid token keys. These are the source of truth and must
// stay in sync with the types. TypeScript's satisfies operator ensures they match.
const FONT_KEYS = {
  display: true,
  body: true,
  mono: true,
} as const satisfies Record<FontKey, true>;

const STEP_KEYS = {
  wordmark: true,
  display: true,
  h1: true,
  h2: true,
  lede: true,
  body: true,
  meta: true,
} as const satisfies Record<StepKey, true>;

const COLOR_KEYS = {
  fg: true,
  'fg-dim': true,
  muted: true,
  accent: true,
  'accent-2': true,
} as const satisfies Record<ColorKey, true>;

function isFontKey(key: unknown): key is FontKey {
  return typeof key === 'string' && Object.prototype.hasOwnProperty.call(FONT_KEYS, key);
}

function isStepKey(key: unknown): key is StepKey {
  return typeof key === 'string' && Object.prototype.hasOwnProperty.call(STEP_KEYS, key);
}

function isColorKey(key: unknown): key is ColorKey {
  return typeof key === 'string' && Object.prototype.hasOwnProperty.call(COLOR_KEYS, key);
}

function round2(n: number): number {
  return Math.round(n * 100) / 100;
}

function clamp(n: number, lo: number, hi: number): number {
  return Math.min(hi, Math.max(lo, n));
}

/**
 * Bring a dragged framing into the range that is guaranteed safe.
 *
 * With `object-fit: cover` the image always covers the frame, so any
 * object-position from 0% to 100% shows image content — the range itself is
 * the bound, and no per-zoom arithmetic is needed. Zoom below 1 is what would
 * actually expose empty frame, so 1 is the floor.
 *
 * Non-finite values (NaN, Infinity) are sanitized to safe defaults to prevent
 * corrupted localStorage from generating invalid CSS.
 */
export function clampFraming(x: number, y: number, zoom: number): ImageEdit {
  return {
    x: round2(clamp(isFinite(x) ? x : 0, 0, 100)),
    y: round2(clamp(isFinite(y) ? y : 0, 0, 100)),
    zoom: round2(clamp(isFinite(zoom) ? zoom : 1, MIN_ZOOM, MAX_ZOOM)),
  };
}

/** Escape a value for use inside a double-quoted CSS attribute selector. */
function cssAttrValue(raw: string): string {
  return raw
    .replace(/\\/g, '\\\\')
    .replace(/"/g, '\\"')
    .replace(/\n/g, '\\a ')
    .replace(/\r/g, '\\d ');
}

export function generateCss(state: PanelState): string {
  const blocks: string[] = [];

  for (const label of Object.keys(state.images).sort()) {
    const raw = state.images[label];
    // Re-clamp numeric values in case they were corrupted in storage (NaN, Infinity, etc.)
    const { x, y, zoom } = clampFraming(raw.x, raw.y, raw.zoom);
    const decls = [`  object-position: ${x}% ${y}%;`];
    // A zoom of exactly 1 is the default; emitting it would be noise in the diff.
    if (zoom !== 1) decls.push(`  --img-zoom: ${zoom};`);
    blocks.push(`.frame[data-label="${cssAttrValue(label)}"] img {\n${decls.join('\n')}\n}`);
  }

  for (const id of Object.keys(state.styles).sort()) {
    const s = state.styles[id];
    const decls: string[] = [];
    // Validate all token keys against runtime allowlists before emitting.
    // This prevents corrupted localStorage values from injecting CSS.
    if (s.font && isFontKey(s.font)) decls.push(`  font-family: var(--font-${s.font});`);
    if (s.step && isStepKey(s.step)) decls.push(`  font-size: var(--step-${s.step});`);
    if (s.color && isColorKey(s.color)) decls.push(`  color: var(--${s.color});`);
    if (decls.length === 0) continue;
    // Prefix with :root to lift specificity from (0,1,0) to (0,2,0) so typography
    // overrides beat ordinary prose rules like .life p (0,1,1) in home.css.
    blocks.push(`:root [data-edit="${cssAttrValue(id)}"] {\n${decls.join('\n')}\n}`);
  }

  return blocks.length === 0 ? HEADER : `${HEADER}\n${blocks.join('\n\n')}\n`;
}
